### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by sbuller** [mcavage/node-bdb#1]
"sh: scripts/postinstall.sh: No such file or directory"

I've cloned the git repo, and run 'sudo npm install .' (npm version 0.3.18). Compilation occurs, but npm can't seem to find the files that are definitely there. I don't know npm well enough to blame it for the problem though. I'd be happiest if node-bdb was searchable with npm.

**Comment by sbuller** [comment]
additionally, the preinstall 'node-waf configure build' fails unless I've already run it.

**Comment by sbuller** [comment]
Works when I use 'sudo npm link .' - I'm satisfied with this solution. I think.

**Comment by mcavage** [comment]
I saw you found npm ln.  That's what I was going to suggest.  I plan to publish both this and node-db in the near future. Just as you saw they need a little polish :)
